<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
import torch

In [8]:
y_onehot = torch.FloatTensor(3, 1)
y_onehot.zero_()

tensor([[0.],
        [0.],
        [0.]])

In [15]:
x = torch.rand(2, 5)
print(x)

torch.zeros(3, 5).scatter_(0, torch.tensor([[0, 1, 2, 0, 0], [2, 0, 0, 1, 2]]), x)


tensor([[0.7424, 0.1836, 0.5277, 0.4061, 0.8913],
        [0.8882, 0.2506, 0.6958, 0.2487, 0.3088]])


tensor([[0.7424, 0.2506, 0.6958, 0.4061, 0.8913],
        [0.0000, 0.1836, 0.0000, 0.2487, 0.0000],
        [0.8882, 0.0000, 0.5277, 0.0000, 0.3088]])

In [13]:
print(y)
y.view(-1, 1)

tensor([[1, 2, 1]])


tensor([[1],
        [2],
        [1]])

In [16]:
torch.tensor([[0, 1, 2, 0, 0], [2, 0, 0, 1, 2]])

tensor([[0, 1, 2, 0, 0],
        [2, 0, 0, 1, 2]])